force_bridge_node:
  ros__parameters:
    # Mass of the object/system in kilograms (0.0 if unused or unknown)
    mass: 0.0
    # Center of Mass coordinate in meters relative to panda_link8
    com_x: 0.0875
    com_y: -0.075
    com_z: 0.0



wrench_service_node:
  ros__parameters:
    # Force threshold along Z axis in Newtons to trigger events/actions
    z_force_threshold: 1.0


motion_smoother_node:
  ros__parameters:
    # true if you want to use tf input, false if you want to use a topic input
    use_tf_input: false
    # Input topic for the target frame (if use_tf_input is false)
    input_topic: '/target_arm'
    # Input frame for the target frame (if use_tf_input is true)
    input_frame: 'object_frame'
    # Output topic for the target frame
    # '/cartesian_compliance_controller/target_frame' to use cartesian compliance controller
    output_topic: '/cartesian_compliance_controller/target_frame'
    # publish rate in Hz and step distance in meters, speed = publish_rate * step_distance
    publish_rate: 10.0
    step_distance: 0.004
    # timeout for the motion smoother in seconds
    timeout: 60.0

